### PR TITLE
Issue 30 automate integration testing

### LINKED ISSUE #30: Automate integration testing
Requires #5 

Create a Github Action for the tests and run them against the live API service (with the url in secrets), triggered on some events (at least once after deployment - perhaps possible to run periodically e.g. on all commits). Add a status badge "Integration tests" to the repo readme.

### PR DESCRIPTION
**Pull request by adrian-golian**
Requires: #129, #133, #134 

Closes #30

### CODE REVIEW

**Comment by adrian-golian** [comment]
Ok, I‘ve tried debugging this, but there’s still an issue running the API locally in the CI. The tests can’t connect to it.

**Comment by adrian-golian** [comment]
The thing that’s missing is R. I’m not sure how to make it available in the Gihub action.

**Comment by adrian-golian** [comment]
Ok, the tests are running now. The remaining issue is that... the API build is failing :/
line 18, in test_games
    assert isinstance(games, list)
AssertionError

**Comment by adrian-golian** [comment]
Ok, it’s that the paths are still /v2.2/. Once the path change to /v2/ is in, this should be fixed.

**Comment by maciej-pomykala** [comment]
Should we squash all the `Update test_api_prod.yml` commits into one for greater clarity of the commit history?

**Comment by adrian-golian** [comment]
Most definitely. Once the CI actually passes.

**Comment by adrian-golian** [comment]
Seems fine now.

**Pull request merged**
