### PR TITLE
Show players who lost in the 'players' array, but with n_cards equal to 0

### LINKED ISSUE #56: In the current game state, mention players who have already lost
Currently, the get state endpoint of the API does not mention players who were playing in the game but have lost. It would be nicer if it did.

The players will be listed with `n_cards = 0`

As discussed on our call.

### PR DESCRIPTION
**Pull request by maciej-pomykala**
Closes #56

### CODE REVIEW

**Comment by maciej-pomykala** [comment]
This has been tested by running a 3-player game until the end

**Comment by adrian-golian** [comment]
This looks ok.
But a general comment about storing the players - since the game already has UUIDs of players, why should it identify the current player by some array index, rather than the UUID. Especially if that array changes/reorders 😱 (so it's good that players aren't kicked off it anymore...)

**Comment by maciej-pomykala** [comment]
Actually, I should change that right now

The `losing_player_i` was moderately useful before I implemented the `find_next_active_player`, but now I think I can get rid of it without adding much code at all

**Comment by maciej-pomykala** [comment]
Done

**Pull request merged**
