### PR TITLE
Change hand_type to set_type, reverse colour ordering and add action_id in indexation.csv

### LINKED ISSUE #36: Reverse card colour ordering
Make colour `3` be the best and colour `0` the worst. Right now it is the other way round.
(i.e. update `indexing.csv`)

### LINKED ISSUE #37: Add action_id and description to indexation.csv
Make the `action_id` to `hand_type` and `detail` fixed, by explicitly storing action_ids in `indexation.csv`.
Make use of the coupling in `/games/{id}/play` endpoint code and anywhere else that might be consuming `indexation.csv`.
Add a `description` field to `indexation.csv` and serve this information in the response of `/games/{id}`, in the `history` key.

### PR DESCRIPTION
**Pull request by maciej-pomykala**
EDIT:
closes #36 , closes #37 
Now colours are ordered from 0-worst to 3-best.

### CODE REVIEW

**Comment by maciej-pomykala** [comment]
If we can agree on these then I can proceed to include this in the documentation

**Comment by adrian-golian** [comment]
Can we use `description` rather than `humanised`? Noun rather than adjective.

**Comment by maciej-pomykala** [comment]
Is `standardised_description` maybe better, to indicate that this sort of becomes law?

**Comment by adrian-golian** [comment]
That's exactly my point. This is not any standard, this is not supposed to be used as a unique identifier because we already have one - `action_id`. Introducing a duplicate "primary identifier" is very very bad. That's why this is meant for informational purposes only - "description".

**Comment by maciej-pomykala** [comment]
I think there is a difference between a standard and a primary identifier. For example, the alpha 3 country codes are a standard, but it's well-understood that this is not how countries should be referred to in diplomatic documents.

This is a standard if we plan on validating players' actions against it. What I mean is: if we use it as a solution to #41 
... which would be a good thing to do, since the `hand_type` + `detail` combination is a sort of a grey area between human interpretation of the names and the machine's mechanism.

**Comment by maciej-pomykala** [comment]
Which reminds me that I have to switch `hand_type` to `set_type` because that's what it's called now

**Comment by adrian-golian** [comment]
> This is a standard if we plan on validating players' actions against it. What I mean is: if we use it as a solution to #41 

Eeexactly. The textual column is not supposed to be standard, this is not supposed to be used for validating players' actions. It's informational, only.

The columns `action_id`, `set_type`, `detail_1`, `detail_2` will be used for validating players' actions.

**Comment by maciej-pomykala** [comment]
What I meant is that we _would not_ use `set_type`, `detail_1` and `detail_2` but we _would_ use the descriptive field

**Comment by adrian-golian** [comment]
While also getting rid of action_id, correct?

**Comment by maciej-pomykala** [comment]
I would leave `action_id` in

**Comment by adrian-golian** [comment]
And either one of the parameters alone would be enough to /play right?

**Comment by maciej-pomykala** [comment]
I was thinking of `action_id` as necessary but we can make them substitutable

**Pull request merged**
