### PR TITLE
Make the API return a meaningful error upon entering an invalid game_uuid

### PR DESCRIPTION
**Pull request by maciej-pomykala**

### CODE REVIEW

**Comment by adrian-golian** [comment]
To avoid leaving a trace merge commit you can do
git rebase develop
with basically the same effect.

**Comment by maciej-pomykala** [comment]
Ok.
In the meantime, can we merge it? I have a fix for #34 ready, but it's on top of that

**Comment by adrian-golian** [comment]
Doesn’t seem complete. It’s checking for the game’s existence in game_data, but it should check the string is a valid UUID first.
What if their “game_uuid” happens to be “& rm -rf ../game_data” (as I hope, need to verify, that “& sudo rm -rf /“ would fail for lack of permission)?

**Comment by maciej-pomykala** [comment]
I think there will be a trade-off between running a detailed regex (which may take time if there are many games being queries) vs checking whether the UUID is composed of only letters, numbers and hyphens. Would you agree with using the latter?

**Comment by adrian-golian** [comment]
1. Checking for “only letters, numbers and hyphens” is almost no validation at all and you might as well skip it.
2. Regex is incredibly efficient and the UUID check is likely faster than you doing the alternative check you proposed.

This consideration is not only premature optimisation (bad), but optimisation at the cost of security (insanely bad). Just check for UUIDs and stop worrying about “speed”.

**Comment by adrian-golian** [comment]
I’m also really surprised there’s no “uuid.validate” in the R package.

**Comment by maciej-pomykala** [comment]
I think the conflict was with the change that only non-started games' privacy can be changed. I resolved and should work.

**Pull request merged**
